[project]
name = "kanji_lab_loader"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
	"regex",
	"tqdm",
	"wanakana-python",
]

[tool.uv]
dev-dependencies = [
	"ruff"
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "UP",
    "B",
    "SIM",
    "I",
]